Track unregistered stale connection count
RedHatInsights/platform-receptor-controller pull request #162
Opened 2020-10-01 13:14 UTC by SteveHNH

RHCLOUD-9224

Signed-off-by: Stephen Adams <tsadams@gmail.com>

2020-10-06 15:52 UTC, dehort requested changes
For RHCLOUD-9224, I was thinking of modifying the connection cleaner util so that it recorded the stale connection cleanup metric.  I added a bit more details to RHCLOUD-9224.  Let me know if we need to discuss.

2020-10-06 15:52 UTC, dehort commented on internal/controller/redis_connector.go
> +		metrics.unregisterStaleConnectionFromRedis.Inc()
This method is used in the case of normal un-registration so I don't think this is the right place for this counter.

2020-10-14 20:55 UTC, SteveHNH commented
@dehort Give it a look now. I moved the metrics collection bit into connection_cleaner (like I was supposed to), and added prometheus push gateway config.

2020-10-15 19:15 UTC, dehort requested changes
This looks good overall.  I left a couple of nit-picky comments.  Sorry, I favor being overly verbose in naming things.  I find it helpful when I come back to the code later down the road.  Let me know what you think!

2020-10-15 19:15 UTC, dehort commented on cmd/connection_cleaner/main.go
> +func pushValues(cfg *config.Config, connCount *Metrics) {
nit-picky:  What do you think about naming this method something a little bit more descriptive?  Something like pushMetricsToPrometheus()?

2020-10-15 19:15 UTC, dehort commented on internal/config/config.go
> +	PROM_PUSH_GW                                       = "PromPushGW"
nit-picky:  Can you make this option name a bit more verbose?  Maybe "Prometheus_Push_Gateway"?

2020-10-15 19:15 UTC, dehort commented on cmd/connection_cleaner/main.go
> +			Name: "receptor_controller_unregister_stale_connection_from_redis_count",
Can we change the name to "receptor_controller_connection_cleaner_unregister_stale_connection_from_redis_count"?  I think I'd like to track this count separately from the "usual" method of removing stale connections.

2020-10-15 20:51 UTC, dehort commented
Does the push gateway require credentials?

2020-10-26 17:40 UTC, SteveHNH commented
> 
> 
> Does the push gateway require credentials?

As far as I know, it does not. We do need to update the network policy to allow our controller to hit it though.

2020-10-30 19:38 UTC, merged